import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import * as Clipboard from "expo-clipboard";
import { useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { EmptyState, palette, PrimaryButton, StatusPill, useContentWidthStyle } from "@/components/agent-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAgent } from "@/lib/agent/agent-provider";
import { router } from "@/lib/navigator";

export default function ArtifactScreen() { const { artifactId } = useLocalSearchParams<{ artifactId: string }>(); const { state, readArtifact } = useAgent(); const contentWidth = useContentWidthStyle(); const artifact = state.artifacts.find((item) => item.id === artifactId); const [content, setContent] = useState(""); const [loading, setLoading] = useState(Boolean(artifact)); const [copied, setCopied] = useState(false); useEffect(() => { if (!artifact) return; setLoading(true); readArtifact(artifact).then(setContent).finally(() => setLoading(false)); }, [artifact, readArtifact]); if (!artifact) return <ScreenContainer className="flex-1"><EmptyState icon="error-outline" title="Artifact bulunamadı" description="Bu dosya silinmiş veya artık bu cihazda erişilebilir olmayabilir." action={<PrimaryButton label="Dosyalara dön" icon="arrow-back" onPress={() => router.back()} />} /></ScreenContainer>; return <ScreenContainer className="flex-1"><ScrollView contentContainerStyle={[styles.content, contentWidth]}><View style={styles.head}><View style={styles.fileIcon}><MaterialIcons name="description" size={27} color={palette.blue} /></View><View style={styles.headText}><Text style={styles.name}>{artifact.name}</Text><View style={styles.metaRow}><StatusPill label={artifact.kind.toUpperCase()} tone="info" /><Text style={styles.meta}>{Math.max(1, Math.round(artifact.size / 1024))} KB</Text></View></View></View><Pressable accessibilityRole="button" accessibilityLabel="Artifact içeriğini kopyala" onPress={() => void Clipboard.setStringAsync(content).then(() => setCopied(true))} style={({ pressed }) => [styles.copy, pressed && styles.pressed]}><MaterialIcons name={copied ? "check" : "content-copy"} size={17} color={palette.blue} /><Text style={styles.copyText}>{copied ? "Kopyalandı" : "İçeriği kopyala"}</Text></Pressable><View style={styles.document}>{loading ? <ActivityIndicator color={palette.blue} /> : <Text selectable style={styles.documentText}>{content}</Text>}</View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 30, gap: 13 }, head: { flexDirection: "row", gap: 12, alignItems: "center" }, fileIcon: { width: 54, height: 54, backgroundColor: palette.blueSoft, borderRadius: 16, alignItems: "center", justifyContent: "center" }, headText: { flex: 1, gap: 7 }, name: { color: palette.navy, fontSize: 18, fontWeight: "900" }, metaRow: { flexDirection: "row", gap: 8, alignItems: "center" }, meta: { color: palette.muted, fontSize: 11 }, copy: { height: 43, borderRadius: 12, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface, flexDirection: "row", gap: 7, justifyContent: "center", alignItems: "center" }, copyText: { color: palette.blue, fontSize: 13, fontWeight: "800" }, document: { backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border, borderRadius: 16, padding: 16, minHeight: 300 }, documentText: { color: palette.navy, fontSize: 13, lineHeight: 21, fontFamily: "monospace" }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] } });
