import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "@/lib/navigator";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { EmptyState, palette, PrimaryButton, StatusPill } from "@/components/agent-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAgent } from "@/lib/agent/agent-provider";
import type { ProviderConnection } from "@/lib/agent/types";

function ConnectionCard({ connection }: { connection: ProviderConnection }) { const { disconnect, setDefaultModel } = useAgent(); return <View style={styles.card}><View style={styles.cardHead}><View style={styles.providerIcon}><MaterialIcons name="smart-toy" size={22} color={palette.blue} /></View><View style={styles.cardText}><Text style={styles.name}>{connection.label}</Text><Text style={styles.provider}>{connection.provider}</Text></View><StatusPill label="BAĞLI" tone="success" /></View><Text style={styles.modelTitle}>Varsayılan model</Text><View style={styles.models}>{connection.models.slice(0, 10).map((model) => <Pressable key={model.id} accessibilityRole="radio" accessibilityLabel={`${model.label} modeli`} accessibilityState={{ checked: connection.defaultModel === model.id }} onPress={() => setDefaultModel(connection.id, model.id)} style={({ pressed }) => [styles.model, connection.defaultModel === model.id && styles.modelActive, pressed && styles.pressed]}><Text style={[styles.modelText, connection.defaultModel === model.id && styles.modelTextActive]} numberOfLines={1}>{model.label}</Text>{connection.defaultModel === model.id ? <MaterialIcons name="check" size={15} color={palette.blue} /> : null}</Pressable>)}</View><Pressable accessibilityRole="button" accessibilityLabel={`${connection.label} bağlantısını kaldır`} hitSlop={6} onPress={() => Alert.alert("Bağlantıyı kaldır", `${connection.label} için cihazdaki API anahtarı silinecek.`, [{ text: "Vazgeç", style: "cancel" }, { text: "Kaldır", style: "destructive", onPress: () => void disconnect(connection.id) }])} style={({ pressed }) => [styles.disconnect, pressed && styles.pressed]}><MaterialIcons name="link-off" color={palette.error} size={17} /><Text style={styles.disconnectText}>Bağlantıyı kaldır</Text></Pressable></View>; }
export default function ProvidersScreen() { const { state } = useAgent(); return <ScreenContainer className="flex-1"><FlatList data={state.connections} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Text style={styles.title}>AI Sağlayıcıları</Text><Text style={styles.subtitle}>Anahtarlar mobilde güvenli depolamaya alınır; hiçbir zaman olay kayıtlarına yazılmaz.</Text><PrimaryButton label="Yeni sağlayıcı bağla" icon="add" onPress={() => router.push("/connect")} /></View>} ListEmptyComponent={<EmptyState icon="key-off" title="Bağlantı yok" description="OpenAI, Anthropic veya OpenRouter anahtarınızı yapıştırarak başlayın." action={<PrimaryButton label="Sağlayıcı bağla" icon="key" onPress={() => router.push("/connect")} />} />} renderItem={({ item }) => <ConnectionCard connection={item} />} /></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 30, gap: 12 }, header: { gap: 8, marginBottom: 5 }, title: { color: palette.navy, fontWeight: "900", fontSize: 24 }, subtitle: { color: palette.muted, lineHeight: 19, fontSize: 13, marginBottom: 5 }, card: { padding: 14, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface, borderRadius: 17, gap: 12 }, cardHead: { flexDirection: "row", alignItems: "flex-start", gap: 10 }, providerIcon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", backgroundColor: palette.blueSoft, borderRadius: 13 }, cardText: { flex: 1 }, name: { color: palette.navy, fontWeight: "900", fontSize: 15, lineHeight: 19 }, provider: { color: palette.muted, fontSize: 11, marginTop: 3, textTransform: "capitalize" }, modelTitle: { color: palette.navy, fontSize: 12, fontWeight: "800" }, models: { gap: 6 }, model: { minHeight: 44, borderWidth: 1, borderColor: palette.border, paddingHorizontal: 10, borderRadius: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, modelActive: { borderColor: palette.blue, backgroundColor: palette.blueSoft }, modelText: { color: palette.muted, fontSize: 12, lineHeight: 16, flex: 1, minWidth: 0 }, modelTextActive: { color: palette.blue, fontWeight: "800" }, disconnect: { flexDirection: "row", gap: 7, alignItems: "center", alignSelf: "flex-start", paddingTop: 2 }, disconnectText: { color: palette.error, fontSize: 12, fontWeight: "800" }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] } });
