import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "@/lib/navigator";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { EmptyState, palette, StatusPill } from "@/components/agent-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAgent } from "@/lib/agent/agent-provider";

export default function FilesScreen() { const { state, activeWorkspace } = useAgent(); const artifacts = state.artifacts.filter((item) => item.workspaceId === activeWorkspace?.id).slice().reverse(); return <ScreenContainer className="flex-1"><FlatList data={artifacts} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Text style={styles.title}>Dosyalar</Text><Text style={styles.subtitle}>Agent çıktıları workspace içindeki artifact alanında tutulur.</Text></View>} ListEmptyComponent={<EmptyState icon="description" title="Artifact bulunmuyor" description="Agent bir dosya ürettiğinde burada açabilir ve görevin bağlamıyla birlikte inceleyebilirsiniz." />} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`${item.name}, ${item.kind} artifact`} onPress={() => router.push({ pathname: "/artifact", params: { artifactId: item.id } })} style={({ pressed }) => [styles.item, pressed && styles.pressed]}><View style={styles.fileIcon}><MaterialIcons name="description" color={palette.blue} size={23} /></View><View style={styles.body}><View style={styles.itemTop}><Text style={styles.name} numberOfLines={2}>{item.name}</Text><StatusPill label={item.kind.toUpperCase()} tone="info" /></View><Text style={styles.preview} numberOfLines={2}>{item.preview}</Text><Text style={styles.meta}>{Math.max(1, Math.round(item.size / 1024))} KB · {new Date(item.createdAt).toLocaleDateString("tr-TR")}</Text></View><MaterialIcons name="chevron-right" color={palette.muted} size={20} /></Pressable>} /></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 30, gap: 10 }, header: { gap: 6, marginBottom: 4 }, title: { color: palette.navy, fontSize: 25, fontWeight: "900" }, subtitle: { color: palette.muted, fontSize: 13, lineHeight: 19 }, item: { flexDirection: "row", alignItems: "center", gap: 11, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border, borderRadius: 16, padding: 13 }, fileIcon: { width: 46, height: 46, backgroundColor: palette.blueSoft, borderRadius: 13, justifyContent: "center", alignItems: "center" }, body: { flex: 1, gap: 4 }, itemTop: { flexDirection: "row", alignItems: "flex-start", gap: 7 }, name: { flex: 1, minWidth: 0, color: palette.navy, fontWeight: "800", fontSize: 14, lineHeight: 18 }, preview: { color: palette.muted, fontSize: 12, lineHeight: 16 }, meta: { color: "#8997A9", fontSize: 10 }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] } });
