import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "@/lib/navigator";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { EmptyState, palette, PrimaryButton, SectionHeading, StatusPill } from "@/components/agent-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAgent } from "@/lib/agent/agent-provider";
import type { AgentRun } from "@/lib/agent/types";

function runTone(status: AgentRun["status"]): "success" | "warning" | "error" | "info" | "neutral" { return status === "completed" ? "success" : status === "failed" ? "error" : status === "waiting_for_permission" ? "warning" : status === "running" || status === "planning" ? "info" : "neutral"; }

export default function HomeScreen() {
  const { state, activeWorkspace } = useAgent();
  const runs = state.runs.filter((run) => run.workspaceId === activeWorkspace?.id).slice().reverse();
  return <ScreenContainer className="flex-1" containerClassName="bg-background"><FlatList data={runs} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}>
    <View style={styles.topRow}><View><Text style={styles.eyebrow}>AKTİF WORKSPACE</Text><Text style={styles.title}>{activeWorkspace?.name ?? "Workspace seçin"}</Text></View><Pressable accessibilityLabel="Ayarlar" onPress={() => router.push("/settings")} style={({ pressed }) => [styles.iconButton, pressed && styles.pressed]}><MaterialIcons name="tune" size={22} color={palette.navy} /></Pressable></View>
    <View style={styles.hero}><View style={styles.heroIcon}><MaterialIcons name="hub" size={28} color="#FFFFFF" /></View><View style={styles.heroText}><Text style={styles.heroTitle}>Bir işi verin, agent düzenlesin.</Text><Text style={styles.heroSub}>{state.connections.length ? "Plan, araç, artifact ve izin akışı tek yerde." : "Başlamak için AI sağlayıcınızı bağlayın."}</Text></View></View>
    {state.connections.length ? <PrimaryButton label="Yeni agent görevi" icon="add" onPress={() => router.push("/agent")} /> : <PrimaryButton label="AI sağlayıcısı bağla" icon="key" onPress={() => router.push("/connect")} />}
    <View style={styles.metrics}><View style={styles.metric}><Text style={styles.metricValue}>{state.connections.length}</Text><Text style={styles.metricLabel}>sağlayıcı</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{state.artifacts.filter((artifact) => artifact.workspaceId === activeWorkspace?.id).length}</Text><Text style={styles.metricLabel}>artifact</Text></View><View style={styles.metric}><Text style={styles.metricValue}>{runs.filter((run) => run.status === "running").length}</Text><Text style={styles.metricLabel}>çalışıyor</Text></View></View>
    <SectionHeading title="Son görevler" />
  </View>} ListEmptyComponent={<EmptyState icon="account-tree" title="Henüz görev yok" description="Hedefinizi verin; agent bağımlılıkları olan planı ve çalışma akışını oluşturur." action={state.connections.length ? <PrimaryButton label="İlk görevi başlat" icon="add" onPress={() => router.push("/agent")} /> : undefined} />} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/agent", params: { runId: item.id } })} style={({ pressed }) => [styles.run, pressed && styles.pressed]}><View style={styles.runTop}><Text style={styles.runTitle} numberOfLines={1}>{item.instruction}</Text><StatusPill label={item.status.replaceAll("_", " ")} tone={runTone(item.status)} /></View><Text style={styles.runMeta}>{item.graph.tasks.filter((task) => task.status === "completed").length}/{item.graph.tasks.length} adım tamamlandı · {new Date(item.startedAt).toLocaleDateString("tr-TR")}</Text></Pressable>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 34, gap: 12 }, header: { gap: 15, paddingBottom: 8 }, topRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, eyebrow: { fontSize: 10, fontWeight: "800", color: palette.muted, letterSpacing: 1.1 }, title: { color: palette.navy, fontSize: 23, fontWeight: "900", marginTop: 4 }, iconButton: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: palette.surface, borderColor: palette.border, borderWidth: 1 }, hero: { borderRadius: 19, padding: 17, flexDirection: "row", alignItems: "center", gap: 13, backgroundColor: palette.navy }, heroIcon: { width: 50, height: 50, alignItems: "center", justifyContent: "center", borderRadius: 16, backgroundColor: palette.blue }, heroText: { flex: 1 }, heroTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "900", marginBottom: 3 }, heroSub: { color: "#C8D8EC", fontSize: 12, lineHeight: 17 }, metrics: { flexDirection: "row", backgroundColor: palette.surface, borderColor: palette.border, borderWidth: 1, borderRadius: 16, overflow: "hidden" }, metric: { flex: 1, alignItems: "center", paddingVertical: 13 }, metricValue: { color: palette.navy, fontSize: 18, fontWeight: "900" }, metricLabel: { color: palette.muted, fontSize: 10, fontWeight: "700", marginTop: 3 }, run: { backgroundColor: palette.surface, padding: 14, borderRadius: 15, borderWidth: 1, borderColor: palette.border, gap: 7 }, runTop: { flexDirection: "row", gap: 8, alignItems: "flex-start", justifyContent: "space-between" }, runTitle: { color: palette.navy, fontWeight: "800", fontSize: 14, flex: 1 }, runMeta: { color: palette.muted, fontSize: 11 }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] } });
