import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useState } from "react";
import { FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { EmptyState, palette, PrimaryButton, StatusPill, useContentWidthStyle } from "@/components/agent-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAgent } from "@/lib/agent/agent-provider";

export default function ProjectsScreen() {
  const { state, activeWorkspace, createWorkspace, selectWorkspace } = useAgent();
  const contentWidth = useContentWidthStyle();
  const insets = useSafeAreaInsets();
  const [visible, setVisible] = useState(false);
  const [name, setName] = useState("");
  const submit = () => { createWorkspace(name); setName(""); setVisible(false); };
  return <ScreenContainer className="flex-1"><FlatList data={state.workspaces.slice().reverse()} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, contentWidth]} ListHeaderComponent={<View style={styles.header}><View><Text style={styles.title}>Projeler</Text><Text style={styles.subtitle}>Her görev, dosya ve karar kendi yerel workspace’inde tutulur.</Text></View><PrimaryButton label="Yeni" icon="add" onPress={() => setVisible(true)} /></View>} ListEmptyComponent={<EmptyState icon="folder-open" title="Workspace oluşturun" description="Görevler ve artifact’ler bağımsız çalışma alanlarında saklanır." action={<PrimaryButton label="İlk workspace" icon="add" onPress={() => setVisible(true)} />} />} renderItem={({ item }) => <Pressable onPress={() => selectWorkspace(item.id)} style={({ pressed }) => [styles.card, activeWorkspace?.id === item.id && styles.active, pressed && styles.pressed]}><View style={styles.icon}><MaterialIcons name="folder" color={palette.blue} size={24} /></View><View style={styles.cardBody}><View style={styles.cardTop}><Text style={styles.cardTitle}>{item.name}</Text>{activeWorkspace?.id === item.id ? <StatusPill label="AKTİF" tone="success" /> : null}</View><Text style={styles.cardMeta}>{item.taskIds.length} görev · {item.artifactIds.length} artifact</Text></View></Pressable>} /><Modal visible={visible} animationType="slide" transparent onRequestClose={() => setVisible(false)}><View style={styles.modalWrap}><View style={[styles.modal, { paddingBottom: Math.max(insets.bottom, 16) + 12 }]}><Text style={styles.modalTitle}>Yeni workspace</Text><Text style={styles.modalText}>İşinizi ayırmak için kısa ve anlaşılır bir ad kullanın.</Text><TextInput autoFocus value={name} onChangeText={setName} placeholder="Örn. Python Araştırması" placeholderTextColor="#91A0B4" style={styles.input} /><View style={styles.modalActions}><PrimaryButton label="Vazgeç" tone="secondary" onPress={() => setVisible(false)} /><PrimaryButton label="Oluştur" icon="add" disabled={!name.trim()} onPress={submit} /></View></View></View></Modal></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 30, gap: 10 }, header: { gap: 14, marginBottom: 8 }, title: { color: palette.navy, fontWeight: "900", fontSize: 25 }, subtitle: { color: palette.muted, fontSize: 13, lineHeight: 19 }, card: { padding: 15, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface, borderRadius: 18, flexDirection: "row", gap: 12, alignItems: "center" }, active: { borderColor: palette.blue, backgroundColor: palette.blueSoft }, icon: { height: 45, width: 45, backgroundColor: palette.blueSoft, borderRadius: 13, justifyContent: "center", alignItems: "center" }, cardBody: { flex: 1, gap: 5 }, cardTop: { flexDirection: "row", justifyContent: "space-between", gap: 8, alignItems: "center" }, cardTitle: { color: palette.navy, fontWeight: "800", fontSize: 15, flex: 1 }, cardMeta: { color: palette.muted, fontSize: 12 }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] }, modalWrap: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(16,36,62,0.24)" }, modal: { backgroundColor: palette.surface, padding: 22, borderTopLeftRadius: 24, borderTopRightRadius: 24, gap: 12 }, modalTitle: { color: palette.navy, fontSize: 20, fontWeight: "900" }, modalText: { color: palette.muted, fontSize: 13, lineHeight: 19 }, input: { borderWidth: 1, borderColor: palette.border, borderRadius: 12, height: 50, paddingHorizontal: 14, color: palette.navy }, modalActions: { flexDirection: "row", gap: 10, justifyContent: "flex-end", marginTop: 6 } });
