import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "@/lib/navigator";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { EmptyState, palette, StatusPill, useContentWidthStyle } from "@/components/agent-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useAgent } from "@/lib/agent/agent-provider";
import type { AgentRun } from "@/lib/agent/types";

const tone = (status: AgentRun["status"]): "success" | "warning" | "error" | "info" | "neutral" => status === "completed" ? "success" : status === "failed" ? "error" : status === "waiting_for_permission" ? "warning" : status === "running" || status === "planning" || status === "queued" ? "info" : "neutral";
export default function TasksScreen() { const { state, activeWorkspace } = useAgent(); const contentWidth = useContentWidthStyle(); const runs = state.runs.filter((run) => run.workspaceId === activeWorkspace?.id).slice().reverse(); return <ScreenContainer className="flex-1"><FlatList data={runs} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, contentWidth]} ListHeaderComponent={<View style={styles.header}><Text style={styles.title}>Görevler</Text><Text style={styles.subtitle}>Planlar, bağımlılıklar ve çalışma durumu kalıcı olarak saklanır.</Text></View>} ListEmptyComponent={<EmptyState icon="checklist" title="Bekleyen görev yok" description="Yeni bir agent görevi başlattığınızda adımlar burada görünür." />} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/agent", params: { runId: item.id } })} style={({ pressed }) => [styles.run, pressed && styles.pressed]}><View style={styles.row}><Text style={styles.runTitle} numberOfLines={2}>{item.instruction}</Text><StatusPill label={item.status.replaceAll("_", " ")} tone={tone(item.status)} /></View><View style={styles.steps}>{item.graph.tasks.map((task) => <View key={task.id} style={styles.step}><MaterialIcons name={task.status === "completed" ? "check-circle" : task.status === "failed" || task.status === "blocked" ? "cancel" : task.status === "running" ? "play-circle-outline" : "radio-button-unchecked"} size={16} color={task.status === "completed" ? palette.success : task.status === "failed" || task.status === "blocked" ? palette.error : task.status === "running" ? palette.blue : palette.muted} /><Text numberOfLines={1} style={[styles.stepText, task.status === "completed" && styles.done]}>{task.title}</Text></View>)}</View></Pressable>} /></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 30, gap: 12 }, header: { gap: 6, marginBottom: 4 }, title: { color: palette.navy, fontSize: 25, fontWeight: "900" }, subtitle: { color: palette.muted, fontSize: 13, lineHeight: 19 }, run: { backgroundColor: palette.surface, borderColor: palette.border, borderWidth: 1, borderRadius: 16, padding: 14, gap: 12 }, row: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 }, runTitle: { color: palette.navy, fontWeight: "800", fontSize: 14, flex: 1, lineHeight: 19 }, steps: { gap: 8, borderTopWidth: 1, borderTopColor: palette.border, paddingTop: 11 }, step: { flexDirection: "row", alignItems: "center", gap: 8 }, stepText: { color: palette.muted, fontSize: 12, flex: 1 }, done: { color: palette.success }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] } });
